language: python
sudo: false

matrix:
  include:
    - python: 3.5
    - python: 3.6
    #PPC64LE
    - arch: ppc64le
      python: 3.5
    - arch: ppc64le
      python: 3.6

before_install:
 # Travis user running build does not have permission to build wheel. Hence, this fix -
  - |
      if [[ "$TRAVIS_CPU_ARCCH" == "ppc64le" ]]; then
        sudo chown -R $USER:$GROUP ~/.cache/pip/wheels
      fi
install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
